export type Client2ScreenDoc = {
  id: string;
  title: string;
  domain: string;
  source: string;
  patterns: string[];
  purpose: string;
  ui: string[];
  rules: string[];
  evidence: string;
};

const COMMON_SOURCE = 'client2/_화면별_구현매핑.md';

export const client2ScreenDocs: Client2ScreenDoc[] = [
  {
    id: 'MA-100',
    title: '회원 홈 대시보드',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/'],
    purpose: '회원이 지역 기반으로 센터를 탐색하고, 나의 센터·이용권·빠른 메뉴로 진입하는 첫 화면입니다.',
    ui: ['지역 선택 헤더와 알림·QR·센터 검색 진입', '배너와 내 주변/역세권 센터 바로가기', '수업 예약·QR 입장·체성분·스토어 빠른 메뉴', '나의 센터 카드(이용권 D-day, 내 예약·QR·이용권 바로가기)', '체험권·추천 센터·추천 강사·최근 본 센터'],
    rules: ['회원 세션 기준으로만 표시합니다.', '나의 센터·추천 데이터는 미등록 상태에서도 빈 상태를 보여줍니다.', '나의 센터 카드는 이용권 잔여 기간을 D-day로 표시합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-001',
    title: '로그인',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/login'],
    purpose: '회원, 트레이너, 골프강사, FC, 스태프가 같은 앱에서 역할별 세션으로 진입하는 화면입니다.',
    ui: ['휴대폰/계정 로그인', '역할별 미리보기 진입', '가입 및 계정 복구 진입'],
    rules: ['관리자 역할은 회원앱 로그인 대상이 아닙니다.', '로그인 성공 후 역할에 맞는 홈으로 이동합니다.', '비밀번호 5회 연속 실패 시 30분간 잠금됩니다.', '탈퇴 처리된 계정은 로그인할 수 없습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-002',
    title: '앱 가입 / CRM 회원 연동',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/register'],
    purpose: 'CRM에 등록된 회원 정보를 앱 계정과 연결하거나 신규 앱 가입을 진행합니다.',
    ui: ['본인 확인 (이름·전화번호)', 'SMS 인증번호 6자리 입력', '비밀번호 설정 (영문+숫자 8자 이상)'],
    rules: ['CRM 회원 매칭 결과에 따라 가입 플로우를 분기합니다.', 'SMS 인증번호는 6자리이며, 비밀번호는 영문과 숫자를 포함해 8자 이상이어야 합니다.', '가입 완료 후 자동 로그인되어 신규 회원 환영(MA-900)으로 진입합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-110',
    title: 'QR 입장',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/qr'],
    purpose: '회원이 센터 입장 또는 수업 출석 처리를 위해 QR을 제시하는 화면입니다.',
    ui: ['동적 QR 코드', '7일 토큰 유효기간 D-day 카드', '보안 코드 회전(60초)', '입장 가능 이용권 안내'],
    rules: ['유효 이용권이 없으면 입장 제한 안내를 우선합니다.', 'QR 토큰은 7일마다 자동 갱신되며 유효기간을 D-day로 표시합니다.', '내부 보안 코드는 60초마다 회전하는 상태로 표현합니다.', '화면 밝기 자동 최대화는 웹앱 한계로 생략합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-111',
    title: '출석 이력',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/attendance'],
    purpose: '회원의 센터 방문, 수업 출석, 결석/노쇼 이력을 월별로 확인합니다.',
    ui: ['월별 캘린더', '출석/결석 상태', '최근 방문 내역'],
    rules: ['수동 출석과 QR 출석을 같은 이력 안에서 구분합니다.', '노쇼 상태는 수업 정책과 함께 표시합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-120',
    title: '수업 예약 목록',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/classes'],
    purpose: '예약 가능한 PT, GX, 골프, 기타 수업을 탐색하고 예약 진입을 제공합니다.',
    ui: ['수업 유형 필터', '날짜/강사/잔여석', '예약 가능 상태'],
    rules: ['수업 유형은 PT/GX/골프/기타 기준입니다.', '정원, 이용권, 예약 마감 상태를 함께 판단합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-121',
    title: '수업 예약 상세',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/classes/:id'],
    purpose: '선택한 수업의 상세 정보와 예약/취소 가능 여부를 확인합니다.',
    ui: ['수업 정보', '강사 정보', '예약/취소 CTA'],
    rules: ['예약 가능 여부는 이용권, 정원, 시간 정책을 모두 반영합니다.', '같은 시간대에 이미 예약이 있으면 중복 예약을 차단합니다.', '횟수제 이용권의 잔여 횟수가 0회면 예약을 차단하고 구매를 안내합니다.', '취소 마감 시간(수업 시작 2시간 전) 이후 취소는 노쇼로 처리될 수 있어 확인을 받습니다.', '시작 시각이 지난 수업은 예약/취소 행동을 노출하지 않습니다.', '상세 화면에서는 하단 탭을 숨깁니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-126',
    title: '수업 후기 / 만족도',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/classes/:id/feedback'],
    purpose: '완료된 수업에 대해 만족도와 후기를 남깁니다.',
    ui: ['별점/만족도', '빠른 태그·한줄 후기', '추천 의향(NPS) 점수'],
    rules: ['완료된 수업만 후기 작성 대상입니다.', '중복 작성 시 기존 후기 수정 흐름으로 이어집니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-122',
    title: '내 예약 / 수업 이력',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/lessons'],
    purpose: '회원이 예정 수업, 완료 수업, 취소/노쇼 이력을 확인합니다.',
    ui: ['예정/완료 탭', '수업 상태 배지', '취소 및 후기 진입'],
    rules: ['예약 상태별 가능한 액션만 노출합니다.', '완료 수업은 후기 작성과 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-123',
    title: 'Golf 예약 / 타석 선택',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/golf-bay'],
    purpose: '골프 회원이 강사 레슨을 예약하거나 타석 현황을 확인해 예약합니다.',
    ui: ['강사 예약/타석 예약 탭', '골프 강사 레슨 슬롯(일시·타석·가격)과 내 레슨 스케줄', '타석 현황 그리드(이용가능/이용중/예약/정비중)'],
    rules: ['골프 타석은 센터 운영 시간과 예약 마감 정책을 따릅니다.', '타석 예약은 1시간 단위이며, 쌍방서명 대상 수업과 연결될 수 있습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-124',
    title: '대기 예약 관리',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/waitlist'],
    purpose: '정원 초과 수업의 대기 신청과 대기 순번을 확인합니다.',
    ui: ['대기 중 수업', '순번', '대기 취소'],
    rules: ['예약 확정 시 알림으로 전환됩니다.', '대기 취소는 즉시 순번에서 제외됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-125',
    title: '강사 상세',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/instructors/:id'],
    purpose: '수업 예약 맥락에서 강사 프로필과 담당 수업을 확인합니다.',
    ui: ['강사 프로필', '전문 분야', '담당 수업'],
    rules: ['예약 가능한 수업과 연결되는 강사 정보만 노출합니다.', '탐색 플랫폼 강사 상세와는 진입 맥락이 다릅니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-127',
    title: '온보딩 시작',
    domain: 'C01 공통-회원 / C08 시스템공통',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/onboarding-welcome'],
    purpose: '신규 회원에게 앱 사용 시작과 기본 설정 진입을 안내합니다.',
    ui: ['환영 메시지', '주요 기능 안내', '설문 시작 CTA'],
    rules: ['신규 회원 또는 온보딩 미완료 회원에게 표시합니다.', '완료 후 홈 또는 설문으로 이동합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-128',
    title: '온보딩 설문',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/onboarding'],
    purpose: '운동 목적, 관심 수업, 건강 정보 동의 등 초기 개인화 정보를 수집합니다.',
    ui: ['단계형 설문', '건강 데이터 항목', '완료 CTA'],
    rules: ['필수 항목은 다음 단계 전에 검증합니다.', '건강 데이터는 동의 상태와 함께 저장되는 전제입니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-130',
    title: '내 프로필 / 마이페이지',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/profile'],
    purpose: '회원 개인 정보, 이용권, 결제, 설정으로 이동하는 개인 허브입니다.',
    ui: ['회원 프로필', '등급/이용권 요약', '마이 메뉴'],
    rules: ['트레이너 역할이 /profile로 진입하면 강사용 탭 기준을 따릅니다.', '개인정보 변경은 설정/동의 화면과 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-131',
    title: '이용권 / 잔여 회차 조회',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/membership', '/membership/:id'],
    purpose: '회원이 보유한 이용권, 잔여 회차, 만료일, 재등록 필요 여부를 확인합니다.',
    ui: ['이용권 카드', '잔여 회차', '만료/정지 상태'],
    rules: ['회원 상태 기준으로 정상/만료/휴면/정지 등을 구분합니다.', '이용권 상세는 해당 이용권의 사용 이력까지 이어집니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-132',
    title: '체성분 / FMS / 건강 데이터',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/body-composition', '/reports', '/settings/health-data', '/workout-analysis', '/diet', '/exercise-guide'],
    purpose: '회원의 체성분, 운동 분석, 건강 데이터 연동 상태를 조회합니다.',
    ui: ['측정 그래프', '리포트 요약', '외부 건강 데이터 연동'],
    rules: ['건강 데이터는 동의 상태를 우선 확인합니다.', '미연동 상태에서도 연결 안내와 빈 상태를 제공합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-133',
    title: '결제 이력 / 영수증',
    domain: 'C01 공통-회원 / C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/payments', '/payments/:paymentId'],
    purpose: '회원의 결제 내역과 결제 완료/영수증 상세를 확인합니다.',
    ui: ['결제 목록', '결제 상태', '영수증/세금계산서 정보'],
    rules: ['결제 완료 화면은 C05 MA-811/MA-850 흐름과 연결합니다.', '실패 결제는 실패 화면으로 분리합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-138',
    title: '재등록 추천 플랜',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/renewal'],
    purpose: '이용권 만료 또는 만료 예정 회원에게 재등록 추천 플랜과 상담/구매 진입을 제공합니다.',
    ui: ['만료 예정 안내', '추천 플랜', '상담/구매 CTA'],
    rules: ['회원 상태와 이용권 만료일을 기준으로 추천을 표시합니다.', 'FC 재등록 상담 흐름과 충돌하지 않도록 회원용 CTA로 제한합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-140',
    title: '상품 목록',
    domain: 'C01 공통-회원 / C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/shop'],
    purpose: '회원이 구매 가능한 이용권, PT, GX, 골프, 리워드 상품을 탐색합니다.',
    ui: ['상품 카테고리', '상품 카드', '장바구니/결제 진입'],
    rules: ['상품 노출은 회원 상태와 판매 가능 상태를 반영합니다.', '상세/옵션/결제 흐름으로 이어집니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-141',
    title: '상품 상세',
    domain: 'C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/shop/:productId'],
    purpose: '선택 상품의 가격, 구성, 사용 조건, 구매 가능 여부를 확인합니다.',
    ui: ['상품 상세 정보', '포함 혜택·결제 안내', '구매 CTA(결제 화면 직행)'],
    rules: ['판매 중지 또는 품절이면 구매 액션을 제한합니다.', '상품 상세에서는 옵션/수량 선택 없이 결제 화면으로 바로 진입합니다(옵션 선택은 별도 결제 옵션 화면).'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-142',
    title: '온라인 구매 / 결제',
    domain: 'C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/checkout/:productId', '/checkout/:productId/option', '/checkout/manual', '/payment/personal'],
    purpose: '상품 옵션 선택부터 결제 요청까지 이어지는 구매 흐름입니다.',
    ui: ['옵션 선택', '쿠폰 1장 선택(보유 쿠폰)', '마일리지 사용', '결제 요약(상품금액·쿠폰할인·마일리지·최종금액)', '결제수단 선택(카드·계좌이체·네이버페이·카카오페이) 후 결제'],
    rules: ['쿠폰은 1장만 적용하며 최소 결제금액 미만이면 비활성화합니다.', '쿠폰 할인과 마일리지를 합산해 최종 결제금액에 반영하고 음수가 되지 않게 합니다.', '직접 개인결제는 제한/대체 안내 기준을 따릅니다.', '결제 실패는 완료로 처리하지 않고 결제 실패 화면(MA-812)으로 분기합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-812',
    title: '결제 실패',
    domain: 'C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/checkout/failure'],
    purpose: '결제 실패 사유와 재시도 또는 이전 단계 복귀를 안내합니다.',
    ui: ['실패 사유', '재시도 CTA', '주문/상품 복귀'],
    rules: ['실패 상태는 결제 완료와 혼동되지 않도록 별도 화면으로 보여줍니다.', '재시도 시 기존 주문 맥락을 유지합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-150',
    title: '알림센터',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/notifications'],
    purpose: '예약, 결제, 리워드, 공지 알림을 한 곳에서 확인합니다.',
    ui: ['알림 목록', '읽음 상태', '알림 유형 필터'],
    rules: ['알림 유형에 따라 연결 화면이 달라집니다.', '리워드 알림은 C06 MA-760 기준을 따릅니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-151',
    title: '센터 정보',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/center'],
    purpose: '회원이 소속 센터의 위치, 운영 시간, 연락처, 시설 정보를 확인합니다.',
    ui: ['센터 기본 정보', '운영 시간', '연락/지도 진입'],
    rules: ['회원 소속 센터 기준으로 표시합니다.', '탐색 플랫폼의 센터 상세와는 구매/탐색 맥락이 다릅니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-152',
    title: '공지사항',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/notices', '/events', '/events/:id'],
    purpose: '센터 공지, 이벤트, 운영 안내를 회원에게 제공합니다.',
    ui: ['공지/이벤트 목록', '상세 내용', '중요 공지 강조'],
    rules: ['소속 센터와 전체 공지를 구분합니다.', '이벤트 상세는 공지 상세 패턴을 따릅니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-153',
    title: '1:1 문의',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/support'],
    purpose: '회원이 센터 또는 운영팀에 문의를 남기고 처리 상태를 확인합니다.',
    ui: ['문의 유형', '내용 입력', '처리 상태'],
    rules: ['문의 접수 후 알림/내 활동과 연결됩니다.', '민감 정보 입력은 최소화하도록 안내합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-154',
    title: '구독 / 자동결제',
    domain: 'C01 공통-회원 / C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/subscription', '/payment-methods'],
    purpose: '자동결제 구독 상태와 결제수단을 관리합니다.',
    ui: ['구독 상태', '다음 결제일', '결제수단 목록'],
    rules: ['자동결제 해지/변경은 확인 절차를 거칩니다.', '결제수단 관리는 C05 MA-840 기준입니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-155',
    title: '설정 / 알림 채널',
    domain: 'C01 공통-회원',
    source: 'client2/C01-공통-회원/회원앱.md',
    patterns: ['/settings'],
    purpose: '회원의 앱 설정, 알림 채널, 개인정보 관련 메뉴를 관리합니다.',
    ui: ['알림 설정', '계정 메뉴', '동의/탈퇴 진입'],
    rules: ['동의와 건강 데이터 설정은 별도 화면에서 관리합니다.', '역할별 설정과 회원 설정을 분리합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-156~159',
    title: '개인정보 / 동의 / 탈퇴',
    domain: 'C01 공통-회원 / C08 시스템공통',
    source: 'client2/C01-공통-회원/운영정책.md',
    patterns: ['/legal', '/consents', '/withdrawal'],
    purpose: '약관, 개인정보, 건강 데이터 동의와 탈퇴 요청을 처리합니다.',
    ui: ['약관 문서', '동의 상태', '탈퇴 확인'],
    rules: ['필수 동의 철회는 서비스 사용 제한을 안내합니다.', '탈퇴는 복구 불가성 확인을 거친 뒤 처리합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-200',
    title: '강사 홈 대시보드',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer'],
    purpose: '트레이너/골프강사가 오늘 수업과 방문 현황을 보고 업무 메뉴로 진입하는 업무 홈입니다.',
    ui: ['오늘 수업 수·오늘 방문 수 요약 카드', '다음 수업 카드', '회원관리·일정관리·운동피드백·공지작성 빠른 메뉴'],
    rules: ['trainer와 golf_trainer 역할만 접근합니다.', '강사 업무 화면에서는 강사용 탭을 사용합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-210',
    title: '수업 캘린더',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/schedule'],
    purpose: '강사가 일/주 단위 수업 일정을 확인합니다.',
    ui: ['캘린더', '수업 상태', '일정 상세 진입'],
    rules: ['담당 수업만 표시합니다.', '수업 상태에 따라 시작/완료/서명 액션으로 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-211',
    title: '강사 수업 목록',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/classes'],
    purpose: '강사가 담당 수업 목록을 상태별로 확인합니다.',
    ui: ['수업 목록', '상태 필터', '유형/상태 배지·일시·장소·참여 회원 수'],
    rules: ['카드에는 수업 유형·상태·일시·장소와 참여 회원 수를 표시합니다.', '상세 화면에서는 탭을 숨깁니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-212',
    title: '수업 시작 / 완료 / 서명',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/classes/:id', '/trainer/classes/:id/signature', '/lesson-sign/:classId'],
    purpose: '강사가 수업 진행 상태를 변경하고 필요한 경우 회원 서명을 받습니다.',
    ui: ['수업 상세', '시작 가능 시간(HH:MM~HH:MM) 안내', '시작/완료 CTA', '쌍방서명 캡처', '원격 서명 24시간 만료 카운트다운·12시간 리마인드', '회원 서명 확인 문구 "수업을 정상 수강했습니다"'],
    rules: ['수업 시작은 예정 시각 전후 15분(±15분) 이내에만 가능합니다.', '골프 수업 서명은 MA-312 기준이며, 원격 서명은 24시간 후 만료(12시간 경과 시 리마인드)되고 만료 시 재요청합니다.', '출석 체크 후에만 수업을 완료할 수 있습니다.', '회원이 서명을 거부하면 매니저에게 에스컬레이션하고 앱에서는 추가 처리하지 않습니다.', '완료 처리 후 회원 이력과 후기 흐름에 반영됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-213',
    title: '노쇼 / 페널티 처리',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/운영정책.md',
    patterns: ['/trainer/penalties'],
    purpose: '강사가 노쇼 또는 페널티 대상 수업을 확인하고 처리합니다.',
    ui: ['페널티 대상 목록', '회원별 누적 단계 배지(경고/주의/예약 제한)', '처리 사유', '면제 처리'],
    rules: ['노쇼 1회는 경고, 2회는 주의, 3회 이상 누적 시 예약 제한 단계로 표시합니다.', '면제 처리 시 누적 횟수에 즉시 반영합니다.', '노쇼 처리는 회원 출석/수업 이력에 반영됩니다.', '정책 기준 없이 임의 페널티를 만들지 않습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-214',
    title: '수업 템플릿 관리',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/templates'],
    purpose: '강사가 반복적으로 쓰는 운동 프로그램 또는 수업 구성 템플릿을 관리합니다.',
    ui: ['템플릿 목록', '운동 구성', '회원 배정 진입'],
    rules: ['템플릿은 담당 회원 프로그램 배정과 연결됩니다.', '삭제/수정은 사용 중 여부를 고려합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-220',
    title: '담당 회원 목록',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/members'],
    purpose: '강사가 본인 담당 회원의 수업/건강/피드백 상태를 확인합니다.',
    ui: ['회원 목록', '상태 배지·연락처·이용권 요약', '상세 진입'],
    rules: ['담당 회원만 표시합니다.', '상세에서는 체성분, 평가, 프로그램 배정으로 이어집니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-221~225',
    title: '강사용 회원 상세 / 기록',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/members/:id', '/trainer/feedback', '/workout-log'],
    purpose: '담당 회원의 상세 정보, 체성분, 평가, 운동 프로그램, 운동 이력을 관리합니다.',
    ui: ['회원 상세', '평가/피드백', '운동 이력 기록'],
    rules: ['담당 권한이 있는 회원만 접근합니다.', '기록은 회원 리포트와 강사 업무 이력에 반영됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-240',
    title: '강사 근무현황 / 성과',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/kpi'],
    purpose: '강사가 본인의 수업 수, 완강, 출석, 성과 지표를 확인합니다.',
    ui: ['KPI 카드', '기간 필터', '성과 추이'],
    rules: ['개인 성과만 표시합니다.', '관리자 정산/평가 화면과 동일한 원천 지표를 기준으로 합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-250',
    title: '강사 프로필',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/profile', '/trainer/profile/market'],
    purpose: '강사용 프로필과 탐색 노출용 마켓 프로필을 관리합니다.',
    ui: ['프로필 정보', '전문 분야', '마켓 노출 정보'],
    rules: ['내부 업무 프로필과 외부 노출 프로필을 구분합니다.', '마켓 노출 정보는 탐색 플랫폼 강사 상세와 연결됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-251~252',
    title: '강사용 알림 / 설정',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/notifications', '/trainer/settings'],
    purpose: '강사 업무 알림과 개인 설정을 관리합니다.',
    ui: ['업무 알림', '설정 항목', '계정 메뉴'],
    rules: ['회원 알림과 강사 알림을 분리합니다.', '역할 세션 기준으로 설정을 저장합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-313',
    title: '레슨 확인서 조회',
    domain: 'C02 트레이너-골프강사',
    source: 'client2/C02-트레이너-골프강사/회원앱.md',
    patterns: ['/trainer/certificates', '/trainer/certificates/:id'],
    purpose: '골프 레슨 등 서명 완료 수업의 확인서를 조회합니다.',
    ui: ['확인서 목록', '서명 상태', '상세 문서'],
    rules: ['서명 완료 건만 확인서로 조회합니다.', '회원/강사 양쪽 서명 데이터와 연결됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-340',
    title: '메신저',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/messages', '/messages/:id', '/trainer/messages', '/trainer/messages/:id'],
    purpose: '회원과 센터/강사 간 상담 또는 안내 메시지를 주고받습니다.',
    ui: ['대화 목록', '대화 상세', '메시지 입력'],
    rules: ['역할과 상대방 권한에 따라 대화방을 제한합니다.', '상담/문의 맥락은 관련 상세 화면과 연결됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-400',
    title: 'FC 홈 대시보드',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc'],
    purpose: 'FC가 리드, 상담, 만료 예정 회원, 성과를 빠르게 확인하는 업무 홈입니다.',
    ui: ['상담 예정', '리드 요약', '성과 카드'],
    rules: ['fc 역할만 접근합니다.', '회원앱 안의 FC 업무 화면으로 관리자 권한을 대체하지 않습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-410~412',
    title: 'FC 리드 / 상담',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc/leads', '/fc/leads/new', '/fc/leads/:id'],
    purpose: 'FC가 7단계 리드 칩 필터로 리드를 보고 상담 이력을 등록/수정합니다.',
    ui: ['7단계 리드 필터(신규·연락완료·상담예정·방문완료·등록완료·미전환·보류)', '상담 등록 폼(유형·방식·단계·결과·유입경로 9종)', '상담 내용 1000자 카운터', '상담 이력 상세'],
    rules: ['상담 유형(상담/OT/체험/재등록상담)·방식(대면/유선/부재)·유입경로 9종을 함께 기록합니다.', '상담 내용은 1000자 이내로 제한합니다.', '결과가 미등록/보류이면 후속 조치 입력을 필수로 합니다.', '상담 단계 등록완료는 수동 저장이 불가하며 "회원 등록 권한이 없어 등록 요청으로 전환됩니다" 안내 후 등록 요청으로 전환합니다.', '등록 후 7일이 지나면 수정할 수 없습니다.', '담당 FC 권한 기준으로 목록과 상세를 제한합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-420~422',
    title: 'FC 담당 회원',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc/members', '/fc/members/:id'],
    purpose: 'FC가 담당 회원 정보, 메모, 재등록 가능성을 확인합니다.',
    ui: ['담당 회원 목록', '회원 상세', '메모/상담 이력'],
    rules: ['담당 범위 밖 회원은 조회하지 않습니다.', '메모는 FC 업무 이력으로 남습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-430~431',
    title: '만료 예정 / 재등록 상담',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc/expiring', '/fc/renewals/new'],
    purpose: '만료 예정 회원을 확인하고 재등록 상담을 등록합니다.',
    ui: ['만료 예정 목록', '재등록 상담 폼', '추천 플랜'],
    rules: ['이용권 만료일과 회원 상태를 기준으로 대상을 산정합니다.', '재등록 상담은 FC 리드/상담 이력과 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-440',
    title: 'FC 성과 / KPI',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc/kpi'],
    purpose: 'FC가 상담, 전환, 재등록 등 본인 성과 지표를 확인합니다.',
    ui: ['KPI 카드', '기간 필터', '전환 지표'],
    rules: ['본인 또는 허용된 담당 범위 지표만 표시합니다.', '관리자 KPI와 같은 정의를 기준으로 합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-451~452',
    title: 'FC 알림 / 설정',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/fc/notifications', '/fc/settings'],
    purpose: 'FC 업무 알림과 계정/업무 설정을 관리합니다.',
    ui: ['업무 알림', '설정 항목', '계정 메뉴'],
    rules: ['회원 알림과 FC 업무 알림을 분리합니다.', '역할 세션 기준으로 설정합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-500',
    title: '스태프 홈',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/staff'],
    purpose: '스태프가 회원 조회, 수동 출석, 수업 일정과 본인 출퇴근을 처리하는 업무 홈입니다.',
    ui: ['빠른 업무 메뉴', '본인 출퇴근 카드(출근/퇴근 1탭 + 본인 인증)', '오늘 운영 현황·차트', '최근 본인 출퇴근 기록', '알림'],
    rules: ['staff 역할만 접근합니다.', '본인 출퇴근은 본인 인증(생체 또는 비밀번호) 후 1탭으로 기록하고 근태 시스템 전송을 시뮬레이션합니다.', '본인 기록만 표시하며 타 직원 출퇴근은 조회할 수 없습니다.', '관리자 화면이 아닌 현장 업무용 최소 기능만 제공합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-510~511',
    title: '스태프 회원 조회',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/staff/members', '/staff/members/:id'],
    purpose: '현장 스태프가 회원을 검색하고 기본 이용 상태를 확인합니다.',
    ui: ['회원 검색', '회원 상세', '이용권/출석 요약'],
    rules: ['스태프 권한에 맞는 조회 정보만 표시합니다.', '민감한 상담/성과 정보는 노출하지 않습니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-520~530',
    title: '스태프 출석 / 일정',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/staff/attendance/manual', '/staff/schedule'],
    purpose: '현장 스태프가 수동 출석 처리와 수업 일정을 확인합니다.',
    ui: ['회원 검색', '수동 출석 처리', '일정 목록'],
    rules: ['수동 출석은 이력에 출처가 남아야 합니다.', '일정 조회는 현장 운영에 필요한 범위로 제한합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-551~552',
    title: '스태프 알림 / 설정',
    domain: 'C03 FC-스태프',
    source: 'client2/C03-FC-스태프/회원앱.md',
    patterns: ['/staff/notifications', '/staff/settings'],
    purpose: '스태프 업무 알림과 앱 설정을 관리합니다.',
    ui: ['업무 알림', '설정 항목', '계정 메뉴'],
    rules: ['스태프 업무 알림은 회원 알림과 분리됩니다.', '역할 세션 기준으로 설정합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-300',
    title: '탐색 홈',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/explore', '/search'],
    purpose: '회원이 센터, 강사, 콘텐츠를 탐색하는 모바일 채널 홈입니다.',
    ui: ['검색', '추천 센터/강사', '카테고리 진입'],
    rules: ['B2C/홈페이지/앱 탐색 채널 기준을 회원앱 모바일 경험으로 풀어냅니다.', '회원앱 안에서는 모바일 탐색 경험으로 구현합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-310~315',
    title: '센터 탐색 / 상세 / 지도',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/centers', '/centers/search', '/centers/:id', '/centers/map'],
    purpose: '주변 센터를 검색하고 상세 정보 또는 지도에서 비교합니다.',
    ui: ['센터 목록', '검색/필터', '센터 상세/지도'],
    rules: ['센터 상세는 탐색 목적의 공개 정보 기준입니다.', '소속 센터 정보 화면과 구분합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-350',
    title: '센터 리뷰',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/centers/:id/reviews', '/centers/:id/review'],
    purpose: '센터 리뷰를 조회하거나 작성합니다.',
    ui: ['리뷰 목록', '리뷰 작성', '평점/태그'],
    rules: ['이용권을 보유(구매)한 회원만 후기를 작성할 수 있습니다.', '별점·동의·30자 이상 본문이 모두 충족되어야 등록됩니다.', '신고/차단 정책은 C07 기준과 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-320~321',
    title: '강사 둘러보기 / 상세',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/trainers', '/trainers/:id'],
    purpose: '외부 탐색 맥락에서 강사 프로필과 수업 가능 정보를 확인합니다.',
    ui: ['강사 카드(프로필 이미지·이름·별점·후기 수·소속 센터·전문 분야 태그)', '전문 분야 필터', '강사 상세(소개·전문 영역·가능 시간·후기)'],
    rules: ['마켓 노출 허용 강사만 표시합니다.', '강사 상세 하단의 1:1 톡·예약 요청은 메신저 상담으로 연결됩니다(수업 상세 직접 예약 아님).'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-330',
    title: '스크랩',
    domain: 'C04 탐색플랫폼',
    source: 'client2/C04-탐색플랫폼/회원앱.md',
    patterns: ['/scrap'],
    purpose: '회원이 저장한 센터, 강사, 콘텐츠를 다시 확인합니다.',
    ui: ['스크랩 목록', '유형 필터', '상세 진입'],
    rules: ['삭제된 대상은 접근 불가 상태로 표시합니다.', '스크랩은 회원 개인 기준입니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-801',
    title: '장바구니',
    domain: 'C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/cart'],
    purpose: '구매 예정 상품을 모아 결제 전 확인합니다.',
    ui: ['장바구니 상품', '금액 합계', '결제 진입'],
    rules: ['판매 불가 상품은 결제 대상에서 제외합니다.', '옵션/수량 변경 시 금액을 즉시 갱신합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-820~831',
    title: '주문 / 환불',
    domain: 'C05 결제주문',
    source: 'client2/C05-결제주문/회원앱.md',
    patterns: ['/orders', '/orders/:id', '/orders/:id/refund'],
    purpose: '주문 내역, 주문 상세, 환불 요청과 환불 진행 상태를 확인합니다.',
    ui: ['주문 목록', '주문 상세', '환불 요청/상태'],
    rules: ['환불 가능 기간과 상품 정책을 확인합니다.', '환불 상태는 주문 상세에 다시 반영됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-700~725',
    title: '리워드 센터 / 쿠폰함',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/coupons'],
    purpose: '회원이 보유 쿠폰, 마일리지, 배지를 탭으로 확인합니다.',
    ui: ['쿠폰/마일리지/배지 탭', '쿠폰 사용 가능 상태', '마일리지 잔액·소멸 예정 안내'],
    rules: ['쿠폰 사용 가능 여부는 기간/대상/상태를 기준으로 합니다.', '마일리지는 결제 옵션 화면에서 선택 시 차감됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-750',
    title: '베스트 랭킹',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/best'],
    purpose: '회원이 인기 센터·강사·상품 랭킹을 확인합니다.',
    ui: ['센터/강사/상품 랭킹 탭', 'TOP3 + 4위 이하 리스트', '카테고리·지역 필터'],
    rules: ['랭킹은 후기/평점/인기 지표 기준으로 정렬합니다.', '랭킹 항목에서 센터/강사/상품 상세로 연결합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-710',
    title: '멤버십 등급 상세',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/membership-grade'],
    purpose: '회원의 등급, 산정 기준, 다음 등급 조건을 안내합니다.',
    ui: ['현재 등급', '등급 혜택', '다음 등급 조건'],
    rules: ['등급은 브론즈/실버/골드/플래티넘/다이아몬드 기준입니다.', '산정 기준은 리워드 정책과 일치해야 합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-720',
    title: '마일리지 조회 / 사용 / 이력',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/mileage'],
    purpose: '회원이 적립/사용 가능한 마일리지와 이력을 확인합니다.',
    ui: ['마일리지 잔액', '적립/사용 이력', '사용 가능 안내'],
    rules: ['소멸 예정 마일리지를 별도로 안내합니다.', '결제 사용 가능 여부는 결제 정책과 함께 판단합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-730~735',
    title: '친구 초대',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/referral'],
    purpose: '친구 초대 링크와 초대 보상 내역을 제공합니다.',
    ui: ['초대 코드/링크', '공유 CTA', '보상 이력'],
    rules: ['보상 지급 조건을 충족한 초대만 적립합니다.', '중복/부정 초대는 보상 제외 기준을 따릅니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-740~750',
    title: '활동 이력 / 통계',
    domain: 'C06 리워드활동',
    source: 'client2/C06-리워드활동/회원앱.md',
    patterns: ['/activity-history'],
    purpose: '회원의 활동, 미션, 통계 정보를 확인합니다.',
    ui: ['활동 이력', '미션 상태', '통계 요약'],
    rules: ['리워드 산정에 쓰이는 활동은 기준과 상태를 명확히 표시합니다.', '리포트 화면과 일부 지표를 공유합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-600',
    title: '커뮤니티 홈',
    domain: 'C07 커뮤니티',
    source: 'client2/C07-커뮤니티/회원앱.md',
    patterns: ['/community'],
    purpose: '회원이 Q&A, FAQ, 내 활동, 신고/차단 관리를 이용하는 커뮤니티 허브입니다.',
    ui: ['Q&A 진입', 'FAQ 진입', '내 활동/신고 메뉴'],
    rules: ['고객센터/커뮤니케이션 운영 기능을 회원앱 모바일 채널로 제공합니다.', '커뮤니티 화면은 신고/차단 정책과 함께 동작합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-601~620',
    title: 'Q&A 목록 / 상세 / 작성',
    domain: 'C07 커뮤니티',
    source: 'client2/C07-커뮤니티/회원앱.md',
    patterns: ['/qna', '/qna/:id'],
    purpose: '회원이 질문을 조회하거나 작성하고 답변 상태를 확인합니다.',
    ui: ['Q&A 목록', '질문 상세', '익명 작성 토글·답변 상태'],
    rules: ['익명으로 작성한 질문은 작성자 이름 대신 "익명"으로 표시됩니다.', '답변 완료 상태는 알림과 내 활동에 반영됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-630',
    title: 'FAQ',
    domain: 'C07 커뮤니티',
    source: 'client2/C07-커뮤니티/회원앱.md',
    patterns: ['/faq'],
    purpose: '자주 묻는 질문을 카테고리별로 제공합니다.',
    ui: ['FAQ 카테고리', '검색', '답변 펼침'],
    rules: ['센터/서비스 공통 FAQ를 구분할 수 있어야 합니다.', '문의 전 자체 해결 흐름을 제공합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-640',
    title: '신고 / 차단 관리',
    domain: 'C07 커뮤니티',
    source: 'client2/C07-커뮤니티/회원앱.md',
    patterns: ['/community/reports'],
    purpose: '회원이 신고 내역과 처리 상태를 확인합니다.',
    ui: ['신고 내역', '상태 필터(검토중/자동숨김/종료)', '처리 상태'],
    rules: ['신고는 커뮤니티 운영정책을 따릅니다.', '검토중/자동숨김/종료 상태를 구분합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-650',
    title: '내 커뮤니티 활동',
    domain: 'C07 커뮤니티',
    source: 'client2/C07-커뮤니티/회원앱.md',
    patterns: ['/community/activity'],
    purpose: '회원이 작성한 질문, 답변, 좋아요 활동을 확인합니다.',
    ui: ['내 질문/답변/좋아요 탭', '답변 상태 배지', '활동 항목에서 Q&A로 연결'],
    rules: ['질문/답변/좋아요 활동을 탭으로 구분해 표시합니다.', 'Q&A 화면으로 다시 연결됩니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-910~970',
    title: '시스템 공통 상태',
    domain: 'C08 시스템공통',
    source: 'client2/C08-시스템공통/회원앱.md',
    patterns: ['/no-network', '/server-maintenance', '/app-update', '/permissions', '/device-info'],
    purpose: '네트워크 오류, 점검, 업데이트, 권한, 디바이스 정보 같은 앱 공통 상태를 안내합니다.',
    ui: ['상태 안내', '재시도/설정 CTA', '디바이스/앱 정보'],
    rules: ['오류 상태에서도 사용자가 다음 행동을 알 수 있어야 합니다.', '권한 요청은 필요한 권한과 사용 목적을 분리해 안내합니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-960',
    title: '디자인 시스템 가이드',
    domain: 'C08 시스템공통',
    source: 'client2/C08-시스템공통/회원앱.md',
    patterns: ['/publishing/member', '/publishing/trainer', '/publishing/fc', '/publishing/staff'],
    purpose: '역할별 화면 퍼블리싱과 디자인 시스템 상태를 확인하는 내부 검수 화면입니다.',
    ui: ['컴포넌트 샘플', '역할별 패턴', '상태별 UI'],
    rules: ['클라이언트 검수용으로 실제 앱 화면과 같은 토큰을 사용합니다.', '운영 사용자용 주요 기능 화면은 아닙니다.'],
    evidence: COMMON_SOURCE,
  },
  {
    id: 'MA-911',
    title: '404 페이지를 찾을 수 없음',
    domain: 'C08 시스템공통',
    source: 'client2/C08-시스템공통/회원앱.md',
    patterns: ['/missing-preview-page'],
    purpose: '존재하지 않는 경로로 진입했을 때 표시되는 의도된 404 상태 화면입니다. 퍼블리싱 갤러리의 404 데모 카드가 이 화면을 노출합니다.',
    ui: ['404 안내 문구', '뒤로가기 CTA', '홈으로 CTA', '하단 탭/앱 프레임 유지'],
    rules: ['존재하지 않는 경로 진입 시 노출되는 정상 동작이며, 누락된 화면이 아닙니다.', '오류 상태에서도 사용자가 홈/뒤로가기로 흐름을 이어갈 수 있어야 합니다.'],
    evidence: COMMON_SOURCE,
  },
];

function normalizePath(pathname: string): string {
  if (!pathname || pathname === '/') {
    return '/';
  }

  return pathname.replace(/\/+$/, '') || '/';
}

function patternToRegex(pattern: string): RegExp {
  const normalized = normalizePath(pattern);
  if (normalized === '/') {
    return /^\/$/;
  }

  const body = normalized
    .split('/')
    .filter(Boolean)
    .map((segment) => {
      if (segment.startsWith(':') || (segment.startsWith('[') && segment.endsWith(']'))) {
        return '[^/]+';
      }

      return segment.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
    })
    .join('/');

  return new RegExp(`^/${body}$`);
}

export function getClient2ScreenDoc(pathname: string): Client2ScreenDoc | undefined {
  const normalized = normalizePath(pathname);

  const exactMatch = client2ScreenDocs.find((doc) =>
    doc.patterns.some((pattern) => normalizePath(pattern) === normalized),
  );

  if (exactMatch) {
    return exactMatch;
  }

  return client2ScreenDocs.find((doc) =>
    doc.patterns.some((pattern) => pattern.includes(':') && patternToRegex(pattern).test(normalized)),
  );
}
