import type { PublishingScreenSpec } from './ui';

function withPreview(path: string, params?: Record<string, string>) {
  const search = new URLSearchParams({ preview: '1', ...(params || {}) });
  return `${path}?${search.toString()}`;
}

export const memberPublishingScreens: PublishingScreenSpec[] = [
  {
    id: 'login',
    title: '로그인',
    route: '/login',
    url: withPreview('/login'),
    category: '계정',
    state: '기본',
    note: '실제 로그인 화면을 그대로 보여줍니다.',
  },
  {
    id: 'register',
    title: '앱 가입 / 연동',
    route: '/register',
    url: withPreview('/register'),
    category: '계정',
    state: '기본',
    note: 'CRM 선등록 후 휴대폰 인증으로 앱 연동하는 실제 화면입니다.',
  },
  {
    id: 'home',
    title: '홈',
    route: '/',
    url: withPreview('/'),
    category: '대시보드',
    state: '기본',
    note: '오늘 수업, 리워드, 공지, 빠른 예약을 포함한 실제 홈입니다.',
  },
  {
    id: 'qr',
    title: 'QR 체크인',
    route: '/qr',
    url: withPreview('/qr'),
    category: '대시보드',
    state: '기본',
    note: '실시간 QR 갱신 UI를 그대로 확인할 수 있습니다.',
  },
  {
    id: 'attendance',
    title: '출석 이력',
    route: '/attendance',
    url: withPreview('/attendance'),
    category: '대시보드',
    state: '기본',
    note: '월간 캘린더와 출석 리스트를 실제 화면으로 보여줍니다.',
  },
  {
    id: 'notifications-all',
    title: '알림센터',
    route: '/notifications',
    url: withPreview('/notifications'),
    category: '대시보드',
    state: '기본',
    note: '전체 알림 상태입니다.',
  },
  {
    id: 'notifications-unread',
    title: '알림센터 - 미읽음',
    route: '/notifications?tab=unread',
    url: withPreview('/notifications', { tab: 'unread' }),
    category: '대시보드',
    state: '탭',
    note: '미읽음만 남긴 상태입니다.',
  },
  {
    id: 'notices',
    title: '공지사항',
    route: '/notices',
    url: withPreview('/notices'),
    category: '대시보드',
    state: '기본',
    note: '센터 공지와 이벤트 목록의 실제 화면입니다.',
  },
  {
    id: 'center',
    title: '센터 정보',
    route: '/center',
    url: withPreview('/center'),
    category: '대시보드',
    state: '기본',
    note: '운영시간, 시설, 트레이너 소개를 포함한 실제 센터 정보 화면입니다.',
  },
  {
    id: 'classes-all',
    title: '수업 예약 - 전체',
    route: '/classes',
    url: withPreview('/classes'),
    category: '예약',
    state: '기본',
    note: '실제 수업 예약 리스트 기본 상태입니다.',
  },
  {
    id: 'classes-pt',
    title: '수업 예약 - PT 요청',
    route: '/classes?type=PT',
    url: withPreview('/classes', { type: 'PT' }),
    category: '예약',
    state: '탭',
    note: '회원이 트레이너 오픈 슬롯을 보고 요청하는 PT 예약 필터 상태입니다.',
  },
  {
    id: 'class-detail-reserved',
    title: '수업 상세 - 확정 수업',
    route: '/classes/101',
    url: withPreview('/classes/101'),
    category: '예약',
    state: '기본',
    note: '이미 확정된 수업 상세 상태입니다.',
  },
  {
    id: 'class-detail-pt-request',
    title: '수업 상세 - PT 요청 가능',
    route: '/classes/2103',
    url: withPreview('/classes/2103'),
    category: '예약',
    state: '기본',
    note: '트레이너 오픈 슬롯에 대해 회원이 예약 요청을 보낼 수 있는 상태입니다.',
  },
  {
    id: 'class-detail-pt-pending',
    title: '수업 상세 - PT 승인 대기',
    route: '/classes/2106',
    url: withPreview('/classes/2106'),
    category: '예약',
    state: '완료',
    note: '예약 요청이 접수되어 트레이너 승인 대기를 보여주는 상태입니다.',
  },
  {
    id: 'class-detail-waitlist',
    title: '수업 상세 - 대기 상태',
    route: '/classes/102',
    url: withPreview('/classes/102'),
    category: '예약',
    state: '완료',
    note: '정원 마감 및 대기 안내 상태입니다.',
  },
  {
    id: 'instructor-detail',
    title: '강사 상세',
    route: '/instructors/1',
    url: withPreview('/instructors/1'),
    category: '예약',
    state: '기본',
    note: '오픈 슬롯 조회, 승인형 예약 요청, 이미 보낸 요청 상태까지 함께 보이는 강사 상세 화면입니다.',
  },
  {
    id: 'waitlist',
    title: '대기 예약 관리',
    route: '/waitlist',
    url: withPreview('/waitlist'),
    category: '예약',
    state: '기본',
    note: '대기열 등록 내역을 실제 화면으로 확인합니다.',
  },
  {
    id: 'lessons-upcoming',
    title: '내 수업 - 예정 / 승인대기',
    route: '/lessons',
    url: withPreview('/lessons'),
    category: '예약',
    state: '기본',
    note: '예정 수업과 트레이너 승인 대기 요청을 함께 보여주는 상태입니다.',
  },
  {
    id: 'lessons-past',
    title: '내 수업 - 완료',
    route: '/lessons?tab=past',
    url: withPreview('/lessons', { tab: 'past' }),
    category: '예약',
    state: '탭',
    note: '완료 수업과 후기 버튼 상태입니다.',
  },
  {
    id: 'class-feedback-form',
    title: '수업 후기 작성',
    route: '/classes/105/feedback',
    url: withPreview('/classes/105/feedback'),
    category: '예약',
    state: '기본',
    note: '실제 후기 작성 폼입니다.',
  },
  {
    id: 'class-feedback-done',
    title: '수업 후기 완료',
    route: '/classes/104/feedback',
    url: withPreview('/classes/104/feedback'),
    category: '예약',
    state: '완료',
    note: '기작성 후기 확인 상태입니다.',
  },
  {
    id: 'lesson-signature',
    title: '수업 서명',
    route: '/lesson-sign/104',
    url: withPreview('/lesson-sign/104'),
    category: '예약',
    state: '기본',
    note: '실제 서명 캔버스 화면입니다.',
  },
  {
    id: 'golf-coach',
    title: '골프 강사 예약 / 내 스케줄',
    route: '/golf-bay?tab=coach',
    url: withPreview('/golf-bay', { tab: 'coach' }),
    category: '골프',
    state: '기본',
    note: '강사 예약 탭과 내 골프 레슨 스케줄 요약이 함께 보이는 상태입니다.',
  },
  {
    id: 'golf-coach-modal',
    title: '골프 강사 예약 확인',
    route: '/golf-bay?tab=coach&modal=coach',
    url: withPreview('/golf-bay', { tab: 'coach', modal: 'coach' }),
    category: '골프',
    state: '모달',
    note: '강사 예약 확인 바텀시트 오픈 상태입니다.',
  },
  {
    id: 'golf-bay',
    title: '골프 타석 예약',
    route: '/golf-bay?tab=bay',
    url: withPreview('/golf-bay', { tab: 'bay' }),
    category: '골프',
    state: '기본',
    note: '타석 현황 탭 기본 상태입니다.',
  },
  {
    id: 'golf-bay-modal',
    title: '골프 타석 예약 확인',
    route: '/golf-bay?tab=bay&modal=bay',
    url: withPreview('/golf-bay', { tab: 'bay', modal: 'bay' }),
    category: '골프',
    state: '모달',
    note: '타석 예약 확인 바텀시트 오픈 상태입니다.',
  },
  {
    id: 'membership-active',
    title: '이용권 - 이용중',
    route: '/membership',
    url: withPreview('/membership'),
    category: '이용권/결제',
    state: '기본',
    note: '이용중 탭과 함께 PT 잔여 회차 요약 카드가 보이는 상태입니다.',
  },
  {
    id: 'membership-expired',
    title: '이용권 - 만료',
    route: '/membership?tab=expired',
    url: withPreview('/membership', { tab: 'expired' }),
    category: '이용권/결제',
    state: '탭',
    note: '만료 이용권 탭 상태입니다.',
  },
  {
    id: 'membership-detail',
    title: '이용권 상세',
    route: '/membership/501',
    url: withPreview('/membership/501'),
    category: '이용권/결제',
    state: '기본',
    note: '활성 이용권 상세와 PT/레슨 차감 이력을 함께 확인하는 상태입니다.',
  },
  {
    id: 'membership-detail-holding',
    title: '이용권 상세 - 홀딩 신청',
    route: '/membership/501?holding=1',
    url: withPreview('/membership/501', { holding: '1' }),
    category: '이용권/결제',
    state: '모달',
    note: '홀딩 신청 모달 오픈 상태입니다.',
  },
  {
    id: 'shop-all',
    title: '상품 스토어',
    route: '/shop',
    url: withPreview('/shop'),
    category: '이용권/결제',
    state: '기본',
    note: '스토어 전체 상품 상태입니다.',
  },
  {
    id: 'shop-gym',
    title: '상품 스토어 - 헬스장',
    route: '/shop?category=gym',
    url: withPreview('/shop', { category: 'gym' }),
    category: '이용권/결제',
    state: '탭',
    note: '헬스장 필터 상태입니다.',
  },
  {
    id: 'product-gym',
    title: '상품 상세 - 헬스장',
    route: '/shop/gym-3m',
    url: withPreview('/shop/gym-3m'),
    category: '이용권/결제',
    state: '기본',
    note: '헬스장 이용권 상세입니다.',
  },
  {
    id: 'product-golf',
    title: '상품 상세 - 골프장',
    route: '/shop/golf-3m',
    url: withPreview('/shop/golf-3m'),
    category: '이용권/결제',
    state: '기본',
    note: '골프장 이용권 상세입니다.',
  },
  {
    id: 'checkout-card',
    title: '결제하기 - 카드',
    route: '/checkout/gym-3m',
    url: withPreview('/checkout/gym-3m', { method: 'CARD', mileage: '3000', agree: '1' }),
    category: '이용권/결제',
    state: '기본',
    note: '카드 결제 선택 상태입니다.',
  },
  {
    id: 'checkout-transfer',
    title: '결제하기 - 계좌이체',
    route: '/checkout/manual',
    url: withPreview('/checkout/manual', {
      method: 'TRANSFER',
      agree: '1',
      name: '헬스장 자유이용 1개월',
      price: '129000',
      category: 'gym',
      subtitle: '개인 결제 페이지에서 생성한 수동 결제 항목',
    }),
    category: '이용권/결제',
    state: '탭',
    note: '계좌이체 안내가 펼쳐진 상태입니다.',
  },
  {
    id: 'checkout-option',
    title: '결제 옵션 선택',
    route: '/checkout/gym-3m/option',
    url: withPreview('/checkout/gym-3m/option'),
    category: '이용권/결제',
    state: '기본',
    note: '강사, 회차, 시작일 등 결제 전 옵션 선택 화면입니다.',
  },
  {
    id: 'checkout-failure',
    title: '결제 실패',
    route: '/checkout/failure',
    url: withPreview('/checkout/failure'),
    category: '이용권/결제',
    state: '에러',
    note: '결제 실패 사유와 재시도 CTA를 확인하는 상태입니다.',
  },
  {
    id: 'cart',
    title: '장바구니',
    route: '/cart',
    url: withPreview('/cart'),
    category: '이용권/결제',
    state: '기본',
    note: '상품을 담아 결제로 이어지는 실제 장바구니 화면입니다.',
  },
  {
    id: 'personal-payment',
    title: '개인 결제',
    route: '/payment/personal',
    url: withPreview('/payment/personal', { category: 'golf', product: 'golf-1m' }),
    category: '이용권/결제',
    state: '기본',
    note: '직접 결제 항목 생성 전 실제 개인 결제 화면입니다.',
  },
  {
    id: 'payment-methods',
    title: '결제수단 관리',
    route: '/payment-methods',
    url: withPreview('/payment-methods'),
    category: '이용권/결제',
    state: '기본',
    note: '등록 카드와 간편결제 수단을 확인하는 화면입니다.',
  },
  {
    id: 'payments',
    title: '결제 내역',
    route: '/payments',
    url: withPreview('/payments'),
    category: '이용권/결제',
    state: '기본',
    note: '목업 영수증 데이터까지 포함된 실제 결제 내역입니다.',
  },
  {
    id: 'payment-receipt',
    title: '영수증',
    route: '/payments/preview-payment-gym',
    url: withPreview(`/payments/${encodeURIComponent('preview-payment-gym')}`),
    category: '이용권/결제',
    state: '완료',
    note: '결제 완료 영수증 상태입니다.',
  },
  {
    id: 'orders',
    title: '내 주문/예약',
    route: '/orders',
    url: withPreview('/orders'),
    category: '이용권/결제',
    state: '기본',
    note: '결제 이력과 예약 상태를 통합해서 보는 실제 목록 화면입니다.',
  },
  {
    id: 'order-detail',
    title: '주문 상세',
    route: '/orders/seed-9001-1',
    url: withPreview('/orders/seed-9001-1'),
    category: '이용권/결제',
    state: '완료',
    note: '주문 상태 타임라인, 결제 정보, 취소/환불 가능 액션을 확인합니다.',
  },
  {
    id: 'order-refund',
    title: '환불 신청',
    route: '/orders/seed-9001-1/refund',
    url: withPreview('/orders/seed-9001-1/refund'),
    category: '이용권/결제',
    state: '기본',
    note: '환불 사유와 환불 계좌 입력 흐름을 확인하는 화면입니다.',
  },
  {
    id: 'renewal',
    title: '재등록 추천 플랜',
    route: '/renewal',
    url: withPreview('/renewal'),
    category: '이용권/결제',
    state: '기본',
    note: '실제 재등록 추천 화면입니다.',
  },
  {
    id: 'profile',
    title: '마이페이지',
    route: '/profile',
    url: withPreview('/profile'),
    category: '리워드/설정',
    state: '기본',
    note: '실제 마이페이지 화면입니다.',
  },
  {
    id: 'scrap',
    title: '찜한 항목',
    route: '/scrap',
    url: withPreview('/scrap'),
    category: '리워드/설정',
    state: '기본',
    note: '찜한 센터, 강사, 상품 탭과 빈 상태를 확인합니다.',
  },
  {
    id: 'coupons-coupon',
    title: '리워드 센터 - 쿠폰',
    route: '/coupons?tab=coupon',
    url: withPreview('/coupons', { tab: 'coupon' }),
    category: '리워드/설정',
    state: '탭',
    note: '쿠폰 탭 상태입니다.',
  },
  {
    id: 'coupons-mileage',
    title: '리워드 센터 - 마일리지',
    route: '/coupons?tab=mileage',
    url: withPreview('/coupons', { tab: 'mileage' }),
    category: '리워드/설정',
    state: '탭',
    note: '포인트를 마일리지로 통일한 실제 화면입니다.',
  },
  {
    id: 'coupons-badge',
    title: '리워드 센터 - 배지',
    route: '/coupons?tab=badge',
    url: withPreview('/coupons', { tab: 'badge' }),
    category: '리워드/설정',
    state: '탭',
    note: '배지 컬렉션 상태입니다.',
  },
  {
    id: 'settings',
    title: '설정',
    route: '/settings',
    url: withPreview('/settings'),
    category: '리워드/설정',
    state: '기본',
    note: '약관/동의/탈퇴 허브 역할을 하는 실제 설정 화면입니다.',
  },
  {
    id: 'health-data-settings',
    title: '건강 데이터 연동 설정',
    route: '/settings/health-data',
    url: withPreview('/settings/health-data'),
    category: '리워드/설정',
    state: '기본',
    note: 'Health Connect 연동 상태, 권한, 동기화 CTA를 확인합니다.',
  },
  {
    id: 'legal-service',
    title: '약관 / 정책 - 서비스',
    route: '/legal',
    url: withPreview('/legal'),
    category: '리워드/설정',
    state: '탭',
    note: '서비스 이용약관 탭입니다.',
  },
  {
    id: 'legal-privacy',
    title: '약관 / 정책 - 개인정보',
    route: '/legal?tab=privacy',
    url: withPreview('/legal', { tab: 'privacy' }),
    category: '리워드/설정',
    state: '탭',
    note: '개인정보 처리방침 탭입니다.',
  },
  {
    id: 'legal-marketing',
    title: '약관 / 정책 - 마케팅',
    route: '/legal?tab=marketing',
    url: withPreview('/legal', { tab: 'marketing' }),
    category: '리워드/설정',
    state: '탭',
    note: '마케팅 수신 안내 탭입니다.',
  },
  {
    id: 'consents',
    title: '동의관리',
    route: '/consents',
    url: withPreview('/consents'),
    category: '리워드/설정',
    state: '기본',
    note: '필수/선택 동의 상태 관리 화면입니다.',
  },
  {
    id: 'withdrawal',
    title: '회원 탈퇴',
    route: '/withdrawal',
    url: withPreview('/withdrawal'),
    category: '리워드/설정',
    state: '기본',
    note: '탈퇴 요청 입력 화면입니다.',
  },
  {
    id: 'body',
    title: '체성분',
    route: '/body-composition',
    url: withPreview('/body-composition'),
    category: '온보딩/진단',
    state: '탭',
    note: '인바디 탭 상태입니다.',
  },
  {
    id: 'fms',
    title: 'FMS / 체형',
    route: '/body-composition?tab=fms',
    url: withPreview('/body-composition', { tab: 'fms' }),
    category: '온보딩/진단',
    state: '탭',
    note: 'FMS 요약 탭 상태입니다.',
  },
  {
    id: 'onboarding-step1',
    title: '온보딩 1단계',
    route: '/onboarding?step=1',
    url: withPreview('/onboarding', { step: '1' }),
    category: '온보딩/진단',
    state: '기본',
    note: '운동 목적 / 강도 입력 단계입니다.',
  },
  {
    id: 'onboarding-step2',
    title: '온보딩 2단계',
    route: '/onboarding?step=2',
    url: withPreview('/onboarding', { step: '2' }),
    category: '온보딩/진단',
    state: '탭',
    note: '통증 / 일정 입력 단계입니다.',
  },
  {
    id: 'onboarding-step3',
    title: '온보딩 완료',
    route: '/onboarding?step=3',
    url: withPreview('/onboarding', { step: '3' }),
    category: '온보딩/진단',
    state: '완료',
    note: '루틴 제안 완료 상태입니다.',
  },
  {
    id: 'workout-log',
    title: '운동일지',
    route: '/workout-log',
    url: withPreview('/workout-log'),
    category: '운동/콘텐츠',
    state: '기본',
    note: '운동 기록 목록 기본 상태입니다.',
  },
  {
    id: 'workout-log-modal',
    title: '운동일지 - 추가 모달',
    route: '/workout-log?modal=add',
    url: withPreview('/workout-log', { modal: 'add' }),
    category: '운동/콘텐츠',
    state: '모달',
    note: '운동 추가 모달 오픈 상태입니다.',
  },
  {
    id: 'workout-analysis',
    title: '운동 분석',
    route: '/workout-analysis',
    url: withPreview('/workout-analysis'),
    category: '운동/콘텐츠',
    state: '기본',
    note: '로컬 운동 로그 기반 분석 화면입니다.',
  },
  {
    id: 'exercise-guide',
    title: '운동 가이드',
    route: '/exercise-guide',
    url: withPreview('/exercise-guide'),
    category: '운동/콘텐츠',
    state: '기본',
    note: '운동 가이드 기본 상태입니다.',
  },
  {
    id: 'exercise-guide-modal',
    title: '운동 가이드 - 상세 모달',
    route: '/exercise-guide?exercise=1',
    url: withPreview('/exercise-guide', { exercise: '1' }),
    category: '운동/콘텐츠',
    state: '모달',
    note: '운동 상세 바텀시트 오픈 상태입니다.',
  },
  {
    id: 'diet',
    title: '식단 관리',
    route: '/diet',
    url: withPreview('/diet'),
    category: '운동/콘텐츠',
    state: '기본',
    note: '샘플 식단 로그가 채워진 상태입니다.',
  },
  {
    id: 'diet-modal',
    title: '식단 관리 - 추가 모달',
    route: '/diet?modal=add&meal=점심',
    url: withPreview('/diet', { modal: 'add', meal: '점심' }),
    category: '운동/콘텐츠',
    state: '모달',
    note: '음식 추가 모달 오픈 상태입니다.',
  },
  {
    id: 'explore',
    title: '탐색 홈',
    route: '/explore',
    url: withPreview('/explore'),
    category: '탐색',
    state: '기본',
    note: '센터/상품 탐색 전용 홈 화면입니다.',
  },
  {
    id: 'centers',
    title: '센터 목록',
    route: '/centers',
    url: withPreview('/centers'),
    category: '탐색',
    state: '기본',
    note: '내 주변 센터 목록과 정렬/필터 상태입니다.',
  },
  {
    id: 'centers-search',
    title: '센터 검색',
    route: '/centers/search',
    url: withPreview('/centers/search'),
    category: '탐색',
    state: '기본',
    note: '장소와 종목 기반 센터 검색 화면입니다.',
  },
  {
    id: 'centers-map',
    title: '센터 지도',
    route: '/centers/map',
    url: withPreview('/centers/map'),
    category: '탐색',
    state: '기본',
    note: '지도 핀과 하단 센터 미니카드가 함께 보이는 화면입니다.',
  },
  {
    id: 'center-detail',
    title: '센터 상세',
    route: '/centers/1',
    url: withPreview('/centers/1'),
    category: '탐색',
    state: '기본',
    note: '센터 소개, 대표 상품, 리뷰, 결제/문의 CTA를 확인합니다.',
  },
  {
    id: 'center-reviews',
    title: '센터 리뷰 목록',
    route: '/centers/1/reviews',
    url: withPreview('/centers/1/reviews'),
    category: '탐색',
    state: '기본',
    note: '센터 리뷰 리스트와 신고 액션을 확인합니다.',
  },
  {
    id: 'center-review-write',
    title: '센터 리뷰 작성',
    route: '/centers/1/review',
    url: withPreview('/centers/1/review'),
    category: '탐색',
    state: '기본',
    note: '별점, 후기 본문, 사진 첨부 상태를 확인하는 작성 화면입니다.',
  },
  {
    id: 'trainers',
    title: '강사 탐색',
    route: '/trainers',
    url: withPreview('/trainers'),
    category: '탐색',
    state: '기본',
    note: '강사 검색과 전문 분야 필터 상태입니다.',
  },
  {
    id: 'trainer-detail',
    title: '강사 프로필',
    route: '/trainers/1',
    url: withPreview('/trainers/1'),
    category: '탐색',
    state: '기본',
    note: '강사 소개, 리뷰, 예약 요청 CTA를 확인합니다.',
  },
  {
    id: 'community',
    title: '커뮤니티',
    route: '/community',
    url: withPreview('/community'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '커뮤니티 홈과 주요 게시판 진입 상태입니다.',
  },
  {
    id: 'community-activity',
    title: '내 커뮤니티 활동',
    route: '/community/activity',
    url: withPreview('/community/activity'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '내 질문, 답변, 댓글 활동 이력을 확인합니다.',
  },
  {
    id: 'community-reports',
    title: '신고 이력',
    route: '/community/reports',
    url: withPreview('/community/reports'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '커뮤니티 신고 처리 상태를 확인합니다.',
  },
  {
    id: 'qna',
    title: 'Q&A',
    route: '/qna',
    url: withPreview('/qna'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '질문 목록, 카테고리 필터, 작성 모달 진입을 확인합니다.',
  },
  {
    id: 'qna-detail',
    title: 'Q&A 상세',
    route: '/qna/1',
    url: withPreview('/qna/1'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '질문 본문과 답변, 채택/신고 상태를 확인합니다.',
  },
  {
    id: 'events',
    title: '이벤트',
    route: '/events',
    url: withPreview('/events'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '이벤트 목록과 진행/종료 상태입니다.',
  },
  {
    id: 'event-detail',
    title: '이벤트 상세',
    route: '/events/1',
    url: withPreview('/events/1'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '이벤트 조건, 대상 상품, 참여 CTA를 확인합니다.',
  },
  {
    id: 'faq',
    title: 'FAQ',
    route: '/faq',
    url: withPreview('/faq'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: 'FAQ 검색과 카테고리 필터 상태입니다.',
  },
  {
    id: 'support',
    title: '1:1 문의',
    route: '/support',
    url: withPreview('/support'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '문의 유형, 제목, 본문 입력 화면입니다.',
  },
  {
    id: 'messages',
    title: '메시지함',
    route: '/messages',
    url: withPreview('/messages'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '센터/강사 문의 대화방 목록입니다.',
  },
  {
    id: 'message-room',
    title: '메시지 상세',
    route: '/messages/1',
    url: withPreview('/messages/1'),
    category: '커뮤니티/고객지원',
    state: '기본',
    note: '대화 내역, 빠른 답변, 첨부 액션을 확인합니다.',
  },
  {
    id: 'mileage',
    title: '마일리지',
    route: '/mileage',
    url: withPreview('/mileage'),
    category: '리워드/설정',
    state: '기본',
    note: '마일리지 적립/사용 내역과 잔액을 확인합니다.',
  },
  {
    id: 'membership-grade',
    title: '회원 등급',
    route: '/membership-grade',
    url: withPreview('/membership-grade'),
    category: '리워드/설정',
    state: '기본',
    note: '회원 등급, 혜택, 다음 등급 조건을 확인합니다.',
  },
  {
    id: 'activity-history',
    title: '활동 이력',
    route: '/activity-history',
    url: withPreview('/activity-history'),
    category: '리워드/설정',
    state: '기본',
    note: '출석, 예약, 리뷰, 결제 활동 타임라인입니다.',
  },
  {
    id: 'referral',
    title: '친구 초대',
    route: '/referral',
    url: withPreview('/referral'),
    category: '리워드/설정',
    state: '기본',
    note: '추천 코드, 공유, 보상 단계 상태입니다.',
  },
  {
    id: 'reports',
    title: '신고 내역',
    route: '/reports',
    url: withPreview('/reports'),
    category: '리워드/설정',
    state: '기본',
    note: '회원 신고/처리 이력을 확인합니다.',
  },
  {
    id: 'search',
    title: '통합 검색',
    route: '/search',
    url: withPreview('/search'),
    category: '탐색',
    state: '기본',
    note: '센터, 강사, 상품 통합 검색 진입 화면입니다.',
  },
  {
    id: 'best',
    title: '베스트 랭킹',
    route: '/best',
    url: withPreview('/best'),
    category: '탐색',
    state: '기본',
    note: '센터/강사/상품 랭킹 목록을 확인합니다.',
  },
  {
    id: 'subscription',
    title: '구독 관리',
    route: '/subscription',
    url: withPreview('/subscription'),
    category: '이용권/결제',
    state: '기본',
    note: '정기 결제/구독 상태와 해지 CTA를 확인합니다.',
  },
  {
    id: 'onboarding-welcome',
    title: '온보딩 환영',
    route: '/onboarding-welcome',
    url: withPreview('/onboarding-welcome'),
    category: '온보딩/진단',
    state: '기본',
    note: '앱 연동 직후 환영 및 권한 안내 화면입니다.',
  },
  {
    id: 'permissions',
    title: '권한 요청',
    route: '/permissions',
    url: withPreview('/permissions'),
    category: '시스템',
    state: '기본',
    note: '푸시, 위치 등 앱 권한 요청 화면입니다.',
  },
  {
    id: 'device-info',
    title: '디바이스 정보',
    route: '/device-info',
    url: withPreview('/device-info'),
    category: '시스템',
    state: '기본',
    note: '앱 버전, OS, 디바이스 상태 확인 화면입니다.',
  },
  {
    id: 'app-update',
    title: '앱 업데이트 안내',
    route: '/app-update',
    url: withPreview('/app-update'),
    category: '시스템',
    state: '기본',
    note: '권장/강제 업데이트 안내 상태입니다.',
  },
  {
    id: 'no-network',
    title: '네트워크 오류',
    route: '/no-network',
    url: withPreview('/no-network'),
    category: '시스템',
    state: '에러',
    note: '오프라인 또는 네트워크 장애 시 재시도 안내 화면입니다.',
  },
  {
    id: 'server-maintenance',
    title: '서버 점검',
    route: '/server-maintenance',
    url: withPreview('/server-maintenance'),
    category: '시스템',
    state: '에러',
    note: '점검 시간과 홈/재시도 CTA를 확인합니다.',
  },
  {
    id: 'not-found',
    title: '404',
    route: '*',
    url: withPreview('/missing-preview-page'),
    category: '기타',
    state: '에러',
    note: '존재하지 않는 경로로 진입한 실제 404 상태입니다.',
  },
];
