import type { PublishingScreenSpec } from '@/publishing/member/ui';

function withPreview(path: string, params?: Record<string, string>) {
  const search = new URLSearchParams({ preview: '1', role: 'trainer', ...(params || {}) });
  return `${path}?${search.toString()}`;
}

export const trainerPublishingScreens: PublishingScreenSpec[] = [
  {
    id: 'trainer-home',
    title: '트레이너 홈',
    route: '/trainer',
    url: withPreview('/trainer'),
    category: '대시보드',
    state: '기본',
    note: '오늘 수업, 방문 현황, 빠른 메뉴를 포함한 트레이너 홈입니다.',
  },
  {
    id: 'trainer-class-list',
    title: '수업 목록',
    route: '/trainer/classes',
    url: withPreview('/trainer/classes'),
    category: '수업운영',
    state: '기본',
    note: '수업 목록과 운영 화면 진입 카드가 보이는 상태입니다.',
  },
  {
    id: 'trainer-class-detail',
    title: '수업 상세 / 출석 체크',
    route: '/trainer/classes/8101',
    url: withPreview('/trainer/classes/8101'),
    category: '수업운영',
    state: '기본',
    note: '수업 시작, 출석 상태 선택, 완료 처리 액션이 보이는 상태입니다.',
  },
  {
    id: 'trainer-class-detail-signature',
    title: '골프 수업 쌍방서명',
    route: '/trainer/classes/8103/signature',
    url: withPreview('/trainer/classes/8103/signature'),
    category: '수업운영',
    state: '완료',
    note: '강사 서명과 회원 서명 단계를 진행하는 쌍방서명 상태입니다.',
  },
  {
    id: 'trainer-members-all',
    title: '회원 관리 - 전체',
    route: '/trainer/members',
    url: withPreview('/trainer/members'),
    category: '회원관리',
    state: '기본',
    note: '전체 회원 리스트 기본 상태입니다.',
  },
  {
    id: 'trainer-members-today',
    title: '회원 관리 - 오늘 방문',
    route: '/trainer/members?filter=today',
    url: withPreview('/trainer/members', { filter: 'today' }),
    category: '회원관리',
    state: '탭',
    note: '오늘 방문 회원만 필터링한 상태입니다.',
  },
  {
    id: 'trainer-members-favorite',
    title: '회원 관리 - 관심회원',
    route: '/trainer/members?filter=favorite',
    url: withPreview('/trainer/members', { filter: 'favorite' }),
    category: '회원관리',
    state: '탭',
    note: '관심회원만 모아 보는 상태입니다.',
  },
  {
    id: 'trainer-member-detail-exercise',
    title: '회원 상세 - 운동기록',
    route: '/trainer/members/1201',
    url: withPreview('/trainer/members/1201'),
    category: '회원관리',
    state: '기본',
    note: '회원 상세 기본 탭인 운동기록 화면입니다.',
  },
  {
    id: 'trainer-member-detail-body',
    title: '회원 상세 - 체성분',
    route: '/trainer/members/1201?tab=body',
    url: withPreview('/trainer/members/1201', { tab: 'body' }),
    category: '회원관리',
    state: '탭',
    note: '체성분 기록 탭 상태입니다.',
  },
  {
    id: 'trainer-member-detail-lesson',
    title: '회원 상세 - 수업이력',
    route: '/trainer/members/1201?tab=lesson',
    url: withPreview('/trainer/members/1201', { tab: 'lesson' }),
    category: '회원관리',
    state: '탭',
    note: '수업 일정, 잔여 회차, 차감 이력을 확인하는 상태입니다.',
  },
  {
    id: 'trainer-member-detail-lesson-golf',
    title: '회원 상세 - 골프 레슨 이력',
    route: '/trainer/members/1203?tab=lesson',
    url: withPreview('/trainer/members/1203', { tab: 'lesson' }),
    category: '회원관리',
    state: '탭',
    note: '골프 레슨 회원의 잔여 회차와 차감 이력을 보는 상태입니다.',
  },
  {
    id: 'trainer-member-detail-evaluation',
    title: '회원 상세 - 평가',
    route: '/trainer/members/1201?tab=evaluation',
    url: withPreview('/trainer/members/1201', { tab: 'evaluation' }),
    category: '회원관리',
    state: '탭',
    note: '평가 작성과 목록 확인 상태입니다.',
  },
  {
    id: 'trainer-member-detail-memo',
    title: '회원 상세 - 메모',
    route: '/trainer/members/1201?tab=memo',
    url: withPreview('/trainer/members/1201', { tab: 'memo' }),
    category: '회원관리',
    state: '탭',
    note: '회원 메모 확인 상태입니다.',
  },
  {
    id: 'trainer-schedule',
    title: '일정 관리',
    route: '/trainer/schedule',
    url: withPreview('/trainer/schedule'),
    category: '일정',
    state: '기본',
    note: '주간 일정과 함께 회원 예약 요청 승인 대기 영역이 같이 보이는 상태입니다.',
  },
  {
    id: 'trainer-schedule-pending',
    title: '일정 관리 - 승인 대기 요청',
    route: '/trainer/schedule',
    url: withPreview('/trainer/schedule'),
    category: '일정',
    state: '완료',
    note: '회원이 요청한 PT 시간대 승인/반려 액션을 확인하는 상태입니다.',
  },
  {
    id: 'trainer-schedule-modal',
    title: '일정 관리 - 수업 추가',
    route: '/trainer/schedule?modal=add',
    url: withPreview('/trainer/schedule', { modal: 'add' }),
    category: '일정',
    state: '모달',
    note: '오픈 슬롯 추가와 회원 지정 즉시 등록을 함께 처리하는 바텀시트 상태입니다.',
  },
  {
    id: 'trainer-penalties',
    title: '노쇼 / 페널티 보드',
    route: '/trainer/penalties',
    url: withPreview('/trainer/penalties'),
    category: '수업운영',
    state: '완료',
    note: '노쇼와 페널티 이력을 모아서 확인하는 상태입니다.',
  },
  {
    id: 'trainer-templates',
    title: '수업 템플릿 관리',
    route: '/trainer/templates',
    url: withPreview('/trainer/templates'),
    category: '수업운영',
    state: '모달',
    note: '수업 템플릿 목록과 신규 템플릿 추가 폼이 함께 보입니다.',
  },
  {
    id: 'trainer-feedback-list',
    title: '운동 피드백 - 목록',
    route: '/trainer/feedback',
    url: withPreview('/trainer/feedback'),
    category: '피드백',
    state: '기본',
    note: '피드백 대상 수업 목록 상태입니다.',
  },
  {
    id: 'trainer-feedback-form',
    title: '운동 피드백 - 작성',
    route: '/trainer/feedback?view=feedback&classId=2102',
    url: withPreview('/trainer/feedback', { view: 'feedback', classId: '2102' }),
    category: '피드백',
    state: '완료',
    note: '참여 회원별 피드백 작성 상태입니다.',
  },
  {
    id: 'trainer-kpi',
    title: '강사 성과 / KPI',
    route: '/trainer/kpi',
    url: withPreview('/trainer/kpi'),
    category: '운영지표',
    state: '기본',
    note: '완료율, 노쇼 수, 활성 회원 수를 보는 KPI 상태입니다.',
  },
  {
    id: 'trainer-notifications',
    title: '트레이너 알림',
    route: '/trainer/notifications',
    url: withPreview('/trainer/notifications'),
    category: '운영지표',
    state: '기본',
    note: '예약 승인, 노쇼, 서명 관련 알림을 확인하는 상태입니다.',
  },
  {
    id: 'trainer-settings',
    title: '트레이너 설정',
    route: '/trainer/settings',
    url: withPreview('/trainer/settings'),
    category: '운영지표',
    state: '탭',
    note: '푸시, 예약, 시스템 알림 토글을 확인하는 상태입니다.',
  },
  {
    id: 'trainer-certificates',
    title: '레슨 확인서 목록',
    route: '/trainer/certificates',
    url: withPreview('/trainer/certificates'),
    category: '운영지표',
    state: '기본',
    note: '골프 레슨 확인서 목록 상태입니다.',
  },
  {
    id: 'trainer-certificate-detail',
    title: '레슨 확인서 상세',
    route: '/trainer/certificates/cert-8103',
    url: withPreview('/trainer/certificates/cert-8103'),
    category: '운영지표',
    state: '완료',
    note: '강사/회원 서명 시각과 확인서 상태를 보는 상세 화면입니다.',
  },
  {
    id: 'trainer-profile',
    title: '트레이너 MY',
    route: '/trainer/profile',
    url: withPreview('/trainer/profile'),
    category: '기타',
    state: '기본',
    note: '트레이너 전용 마이페이지 상태입니다.',
  },
];
