import type { PublishingScreenSpec } from '@/publishing/member/ui';

function withPreview(path: string, params?: Record<string, string>) {
  const search = new URLSearchParams({ preview: '1', role: 'trainer', ...(params || {}) });
  return `${path}?${search.toString()}`;
}

export const trainerPublishingScreens: PublishingScreenSpec[] = [
  {
    id: 'trainer-home',
    title: '트레이너 홈',
    route: '/trainer',
    url: withPreview('/trainer'),
    category: '대시보드',
    state: '기본',
    note: '오늘 수업, 방문 현황, 빠른 메뉴를 포함한 트레이너 홈입니다.',
  },
  {
    id: 'trainer-members-all',
    title: '회원 관리 - 전체',
    route: '/trainer/members',
    url: withPreview('/trainer/members'),
    category: '회원관리',
    state: '기본',
    note: '전체 회원 리스트 기본 상태입니다.',
  },
  {
    id: 'trainer-members-today',
    title: '회원 관리 - 오늘 방문',
    route: '/trainer/members?filter=today',
    url: withPreview('/trainer/members', { filter: 'today' }),
    category: '회원관리',
    state: '탭',
    note: '오늘 방문 회원만 필터링한 상태입니다.',
  },
  {
    id: 'trainer-members-favorite',
    title: '회원 관리 - 관심회원',
    route: '/trainer/members?filter=favorite',
    url: withPreview('/trainer/members', { filter: 'favorite' }),
    category: '회원관리',
    state: '탭',
    note: '관심회원만 모아 보는 상태입니다.',
  },
  {
    id: 'trainer-member-detail-exercise',
    title: '회원 상세 - 운동기록',
    route: '/trainer/members/1201',
    url: withPreview('/trainer/members/1201'),
    category: '회원관리',
    state: '기본',
    note: '회원 상세 기본 탭인 운동기록 화면입니다.',
  },
  {
    id: 'trainer-member-detail-body',
    title: '회원 상세 - 체성분',
    route: '/trainer/members/1201?tab=body',
    url: withPreview('/trainer/members/1201', { tab: 'body' }),
    category: '회원관리',
    state: '탭',
    note: '체성분 기록 탭 상태입니다.',
  },
  {
    id: 'trainer-member-detail-evaluation',
    title: '회원 상세 - 평가',
    route: '/trainer/members/1201?tab=evaluation',
    url: withPreview('/trainer/members/1201', { tab: 'evaluation' }),
    category: '회원관리',
    state: '탭',
    note: '평가 작성과 목록 확인 상태입니다.',
  },
  {
    id: 'trainer-member-detail-memo',
    title: '회원 상세 - 메모',
    route: '/trainer/members/1201?tab=memo',
    url: withPreview('/trainer/members/1201', { tab: 'memo' }),
    category: '회원관리',
    state: '탭',
    note: '회원 메모 확인 상태입니다.',
  },
  {
    id: 'trainer-schedule',
    title: '일정 관리',
    route: '/trainer/schedule',
    url: withPreview('/trainer/schedule'),
    category: '일정',
    state: '기본',
    note: '주간 일정 리스트 기본 상태입니다.',
  },
  {
    id: 'trainer-schedule-modal',
    title: '일정 관리 - 수업 추가',
    route: '/trainer/schedule?modal=add',
    url: withPreview('/trainer/schedule', { modal: 'add' }),
    category: '일정',
    state: '모달',
    note: '수업 추가 바텀시트가 열린 상태입니다.',
  },
  {
    id: 'trainer-feedback-list',
    title: '운동 피드백 - 목록',
    route: '/trainer/feedback',
    url: withPreview('/trainer/feedback'),
    category: '피드백',
    state: '기본',
    note: '피드백 대상 수업 목록 상태입니다.',
  },
  {
    id: 'trainer-feedback-form',
    title: '운동 피드백 - 작성',
    route: '/trainer/feedback?view=feedback&classId=2102',
    url: withPreview('/trainer/feedback', { view: 'feedback', classId: '2102' }),
    category: '피드백',
    state: '완료',
    note: '참여 회원별 피드백 작성 상태입니다.',
  },
  {
    id: 'trainer-profile',
    title: '트레이너 MY',
    route: '/profile',
    url: withPreview('/profile'),
    category: '기타',
    state: '기본',
    note: '트레이너 전용 마이페이지 상태입니다.',
  },
];
